add two ci steps

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -79,6 +79,16 @@ jobs:
       - if: needs.diff_lean_files.outputs.check_lean == 'true'
         # Lean cannot run its tests in the nix sandbox because `elan` will download things
         run: nix develop --command bash -c "cd tests/lean && make"
+      - if: needs.diff_lean_files.outputs.check_lean == 'true'
+        # Confirm that ExtractBuiltinLean.ml is up-to-date.
+        run: |
+          nix develop --command bash -c "make extract-lean-std"
+          git diff --exit-code -- src/extract/ExtractBuiltinLean.ml || { echo "ERROR: ExtractBuiltinLean.ml is out of date. Run 'make extract-lean-std'."; exit 1; }
+      - if: needs.diff_lean_files.outputs.check_lean == 'true'
+        # Confirm that LeanKeywords.ml is up-to-date.
+        run: |
+          nix develop --command bash -c "make extract-lean-keywords"
+          git diff --exit-code -- src/extract/LeanKeywords.ml || { echo "ERROR: LeanKeywords.ml is out of date. Run 'make extract-lean-keywords'."; exit 1; }
 
   charon-pin-is-forward:
     needs: [select-runner]
